function myf(){
    head.style = 'background-color:rgb(2, 2, 54);'
    colorChange.style.backgroundColor = 'orangered'
    navbar.style.backgroundColor = 'rgb(2, 2, 54)'
    span1.style.color = 'orangered'
    document.querySelector('.nav-link').style.color  = 'orangered'
    document.querySelector('.contact').style.color  = 'orangered'
    document.querySelector('.blog').style.color  = 'orangered'
    btnLight.style = 'color: orangered;background-color:rgb(2, 2, 54);border-right: solid 1px orangered;'
    btnDark.style = 'color: orangered;background-color:rgb(2, 2, 54);border-right: solid 1px orangered;'
    search.style.color = 'orangered' 
    span2.style.color = 'orangered'
    welcomeText.style.backgroundColor = 'rgb(2, 2, 54)'
    centerTop.style.backgroundColor = 'rgb(2, 2, 54)'
    centerUnder.style.backgroundColor = 'rgb(2, 2, 54)'
    firstRow.style.backgroundColor = 'rgb(2, 2, 54)'
    middleRow.style.backgroundColor = 'rgb(2, 2, 54)'
    lastRow.style.backgroundColor = 'rgb(2, 2, 54)'
    footer.style.backgroundColor = 'rgb(2, 2, 54)'
}

function myff(){
    head.style = 'background-color:orangered;'
    colorChange.style.backgroundColor = 'rgb(2, 2, 54)'
    navbar.style.backgroundColor = 'orangered'
    span1.style.color = 'rgb(2, 2, 54)'
    document.querySelector('.nav-link').style.color  = 'rgb(2, 2, 54)'
    document.querySelector('.contact').style.color  = 'rgb(2, 2, 54)'
    document.querySelector('.blog').style.color  = 'rgb(2, 2, 54)'
    btnLight.style = 'color: rgb(2, 2, 54);;background-color:orangered;border-right: solid 1px  rgb(2, 2, 54);'
    btnDark.style = 'color: rgb(2, 2, 54);;background-color: orangered;border-right: solid 1px  rgb(2, 2, 54);'
    search.style.color = 'rgb(2, 2, 54)'
    span2.style.color = 'rgb(2, 2, 54)'
    welcomeText.style.backgroundColor = 'orangered'
    centerTop.style.backgroundColor = 'orangered'
    centerUnder.style.backgroundColor = 'orangered'
    firstRow.style.backgroundColor = 'orangered'
    middleRow.style.backgroundColor = 'orangered'
    lastRow.style.backgroundColor = 'orangered'
    footer.style.backgroundColor = 'orangered'
}